import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/shared/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.vue',
    './app/presentation/**/*.{vue,js,ts}',
    './app/plugins/**/*.{js,ts}',
    './app/app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-dim': '#cbdbf5',
        'tertiary': '#1b3c70',
        'surface-container-high': '#dce9ff',
        'status-error': '#ef4444',
        'surface-container': '#e5eeff',
        'surface-bright': '#f8f9ff',
        'on-background': '#0b1c30',
        'primary-fixed': '#d2e4ff',
        'status-success': '#10b981',
        'on-primary-fixed-variant': '#004880',
        'surface-variant': '#d3e4fe',
        'on-primary-fixed': '#001c37',
        'on-secondary-fixed-variant': '#574500',
        'inverse-surface': '#213145',
        'tertiary-fixed': '#d7e2ff',
        'error': '#ba1a1a',
        'background': '#f8f9ff',
        'on-surface': '#0b1c30',
        'secondary-fixed': '#ffe089',
        'on-secondary-fixed': '#241a00',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed-dim': '#a1c9ff',
        'secondary': '#745b00',
        'surface-container-highest': '#d3e4fe',
        'error-container': '#ffdad6',
        'secondary-container': '#fcd353',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#1961a1',
        'on-tertiary-fixed-variant': '#26467a',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#eac243',
        'primary-container': '#005696',
        'primary': '#003e6f',
        'on-tertiary-fixed': '#001a40',
        'on-primary-container': '#a5cbff',
        'on-error-container': '#93000a',
        'deep-navy': '#0b1120',
        'inverse-primary': '#a1c9ff',
        'outline': '#727781',
        'on-primary': '#ffffff',
        'status-warning': '#f59e0b',
        'industrial-bg': '#f8fafc',
        'surface': '#f8f9ff',
        'outline-variant': '#c1c7d2',
        'on-tertiary-container': '#b0c9ff',
        'on-surface-variant': '#414750',
        'tertiary-container': '#355489',
        'tertiary-fixed-dim': '#acc7ff',
        'on-secondary-container': '#725a00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'container-padding': '24px',
        'unit': '4px',
        'stack-md': '16px',
        'gutter': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'body-sm': ['var(--app-font-sans)'],
        'headline-lg': ['var(--app-font-sans)'],
        'body-md': ['var(--app-font-sans)'],
        'body-lg': ['var(--app-font-sans)'],
        'label-caps': ['var(--app-font-sans)'],
        'data-mono': ['var(--app-font-mono)'],
        'headline-md': ['var(--app-font-sans)'],
        'display-lg': ['var(--app-font-sans)'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-caps': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0.05em',
            fontWeight: '700',
          },
        ],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': [
          '48px',
          {
            lineHeight: '56px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
      },
      keyframes: {
        'fade-in': {
          '0%': {
            opacity: '0',
            transform: 'translateY(6px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out both',
      },
    },
  },
  plugins: [],
} satisfies Config
